//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradingAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName,Symbol,ExchangeName
        ///SteadyMed Ltd.,STDY,NASDAQ
        ///O2Micro International Limited,OIIM,NASDAQ
        ///&quot;Kandi Technologies Group, Inc.&quot;,KNDI,NASDAQ
        ///&quot;Codexis, Inc.&quot;,CDXS,NASDAQ
        ///&quot;MRV Communications, Inc.&quot;,MRVC,NASDAQ
        ///&quot;Foundation Building Materials, Inc.&quot;,FBM,NYSE
        ///argenx SE,ARGX,NASDAQ
        ///ZIOPHARM Oncology Inc,ZIOP,NASDAQ
        ///&quot;Dillard&apos;s, Inc.&quot;,DDS,NYSE
        ///Nuveen New York Municipal Value Fund 2,NYV,NYSE
        ///Century Aluminum Company,CENX,NASDAQ
        ///Tsakos Energy Navigation Ltd,TNP^E,NYSE
        ///&quot;Werner Enterprises, Inc.&quot;,WERN,NASDAQ
        ///Unisy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompanyData {
            get {
                return ResourceManager.GetString("CompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,Symbol,Exchange,LastPrice,Change,ChangePercent,Timestamp,MSDate,MarketCap,Volume,ChangeYTD,ChangePercentYTD,High,Low,Open
        ///Apple Inc,AAPL,NASDAQ,524.49,15.6,3.06549549018453,Wed Oct 23 13:39:19 UTC-06:00 2013,41570.568969907,476497591530,397562,532.1729,-1.44368493773359,52499,519.175,519.175
        ///.
        /// </summary>
        internal static string TradingData {
            get {
                return ResourceManager.GetString("TradingData", resourceCulture);
            }
        }
    }
}
